---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-family-azure
spec:
  package: xpkg.upbound.io/upbound/provider-family-azure:v0.34.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azure-azure
spec:
  package: xpkg.upbound.io/upbound/provider-azure-azure:v0.34.0
---
apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: example-rg-crossplane
spec:
  forProvider:
    location: West Europe
    tags:
      provisioner: crossplane
