{{- range $key,$val := .Values.tenants }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $val.name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:  
    repoURL: https://github.com/andresmanzanaressouthworks/argocd.git
    targetRevision: HEAD
    path: poc/argocd/apps/client-apps
    helm:
      values: |
        tenant: {{ $val.name }}
        provider_config:
          client_id: {{ $val.provider_config.client_id }}
          subscription_id: {{ $val.provider_config.subscription_id }}
          tenant_id: {{ $val.provider_config.tenant_id }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
{{- end }}
