{{- range $key,$val := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s-%s" $.Values.tenant $key }}
spec:
  project: default
  source:
    repoURL: {{ $val.source.repoURL }}
    targetRevision: HEAD
    path: {{ tpl $val.source.path $ }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd #{{ $.Values.tenant }}
{{- end }}