---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s-%s" .Values.name "nginx" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/andresmanzanaressouthworks/argocd.git
    targetRevision: HEAD
    path: poc/argocd/apps/services/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.name }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s-%s" .Values.name "azure-resources" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/andresmanzanaressouthworks/argocd.git
    targetRevision: HEAD
    path: poc/argocd/apps/services/azure-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.name }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s-%s" .Values.name "crossplane-auth" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/andresmanzanaressouthworks/argocd.git
    targetRevision: HEAD
    path: poc/argocd/apps/services/azure-resources
    helm:
      values: |
        tenant: {{ .Values.name }}
        provider_config:
          client_id: {{ .Values.provider_config.client_id }}
          subscription_id: {{ .Values.provider_config.subscription_id }}
          tenant_id: {{ .Values.provider_config.tenant_id }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.name }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
