{{- range $key,$val := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
spec:
  destination:
    namespace: {{ $.Values.default.app.destination.namespace }}
    server: {{ $.Values.default.app.destination.server }}
  project: {{ $.Values.envName }}
  source:
    repoURL: {{ $val.source.repoURL }}
    targetRevision: HEAD
    path: {{ tpl $val.source.path $ }}
{ - end }}