apiVersion: v2
name: flywheel-crossplane
description: A Flywheel flavored Crossplane installation Helm Chart

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: crossplane
    version: 1.12.2
    repository: https://charts.crossplane.io/stable
    alias: crossplane