---
apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: {{ printf "%s-%s" .Values.name "rg" }}
  namespace: {{ .Values.name }}
spec:
  forProvider:
    location: {{ .Values.location }}
    providerConfigRef:
      name: {{ printf "%s-%s" .Values.name "azure-provider-config" }}
